### ISSUE TITLE
OM 2.0 revision 1.1 in Beta

### ISSUE THREAD

**Issue by epicureanism** [opengeospatial/te-releases#203]
https://github.com/opengeospatial/ets-om20/milestone/2

**Comment by lgoltz** [comment]
## Create release
as described in https://github.com/opengeospatial/cite/wiki/Releasing-Tests-to-the-OGC-Testing-Infrastructure

- [ ] In the [OGC release tracker](https://github.com/opengeospatial/te-releases/issues) assign the issue to a milestone.
- [ ] Check that the issues in the ETS issue tracker are properly written and associated to the correct milestone.
- [ ] Close issues in the ETS issue tracker.
- [ ] Update the release file csv (repository: https://github.com/opengeospatial/teamengine-builder).
- [ ] Clone the repository, ensure that the master branch is active and up to date.
- [ ] Do the release. Process involves creating a revision based on the pom.xml version, updating the GitHub page, tag, and updating the revision on the pom for the next release. 
   - Check if Maven configuration has been updated: https://github.com/opengeospatial/cite/wiki/How-to-create-Releases-with-Maven.
   - Create release by executing following commands:
```
mvn -Dresume=false -DdryRun=true release:prepare
mvn -Dresume=false release:prepare
git checkout [RELEASE_TAG]
mvn clean site-deploy
```
- [ ] Close milestore in the ETS issue tracker.
- [ ] Install new releases on beta environment: http://cite.opengeospatial.org/te2/.
- [ ] Close issues in [OGC release tracker](https://github.com/opengeospatial/te-releases/issues).
- [ ] Announce to CITE forum and CITE SC lists the new release.

**Comment by lgoltz** [comment]
Remaining steps will be done in https://github.com/opengeospatial/cite-private/issues/46.
