### ISSUE TITLE
CAT 3.0 revision 1.2 in Beta

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/te-releases#215]
https://github.com/opengeospatial/ets-cat30/milestone/7

**Comment by dstenger** [comment]
#### Prepare release (for each test suite individually)

- [ ]  The master branch should contain the latest "stable" version. Make sure all verified pull requests are merged.
- [ ]  Make sure it builds properly running `mvn clean install site`.
- [ ] Test locally the master branch with the [reference implementation](https://github.com/opengeospatial/cite/wiki/Reference-Implementations), if there is one.
	- If it is OK, continue, if not create or update an issue, in the issue tracker of that test.
- [ ] Review closed issues to be included in the release. 
	- Update title if appropriate.
	- Tag, if they are not tagged with the milestone number.
- [ ] Update release notes, usually the file is at src/site/markdown/relnotes.md.
	- Add a new title for the revision, if there is not one already.
	- Copy the issues to be included in the release, link and title.
	- Add any other highlights.
- [ ] Create a new issue in the [OGC release tracker](https://github.com/opengeospatial/te-releases/issues) and set label `approved-by-test-lead`.
	- Write a title for the issue should containing: [Abbreviation] [version] revision [revision] in *Beta*. For example: WFS 1.1 revision 1.23 in Beta. It should always be in Beta. OGC staff will create the issue related to making the releases in the production, official web site.

**Comment by dstenger** [comment]
#### Create release (for each test suite individually)

- [ ] In the [OGC release tracker](https://github.com/opengeospatial/te-releases/issues) assign the issue to a milestone.
- [ ] Check that the issues and pull requests in the ETS issue tracker are properly written and associated to the correct milestone. Make sure issues are closed in the ETS issue tracker.
- Do the release. Process involves creating a revision based on the pom.xml version, updating the GitHub page, tag, and updating the revision on the pom for the next release. 
   - [ ] Check if Maven configuration has been updated: [How to create Releases with Maven](https://github.com/opengeospatial/cite/wiki/How-to-create-Releases-with-Maven).
   - [ ] Create release with [Jenkins](http://build.opengeospatial.org/jenkins/).
- [ ] Close milestone in the ETS issue tracker.
