### ISSUE TITLE
OM 2.0 revision 0.3 in Beta

### ISSUE THREAD

**Issue by epicureanism** [opengeospatial/te-releases#256]

**Comment by dstenger** [comment]
#### Create release (for each test suite individually)

- [ ] In the [OGC release tracker](https://github.com/opengeospatial/te-releases/issues) assign the issue to a milestone.
- [ ] Check that the issues and pull requests in the ETS issue tracker are properly written and associated to the correct milestone. Make sure issues are closed in the ETS issue tracker.
- Do the release. Process involves creating a revision based on the pom.xml version, updating the GitHub page, tag, and updating the revision on the pom for the next release. 
   - [ ] Check if Maven configuration has been updated: [How to create Releases with Maven](https://github.com/opengeospatial/cite/wiki/How-to-create-Releases-with-Maven).
   - [ ] Create release with [Jenkins](http://build.opengeospatial.org/jenkins/).
- [ ] Close milestone in the ETS issue tracker.
- [ ] Set label `ready-for-installation`.

**Comment by dstenger** [comment]
Release is currently blocked as I do not have permissions for repository.

@bermud Can you please grant me permissions?

**Comment by dstenger** [comment]
Permissions were granted.

**Comment by dstenger** [comment]
TODO: Create Docker Hub repository.

**Comment by dstenger** [comment]
Docker Hub repository was created: https://hub.docker.com/r/ogccite/ets-om20
