### ISSUE TITLE
CDB 1.0 revision 0.4 in Beta

### ISSUE THREAD

**Issue by openfirmware** [opengeospatial/te-releases#269]
I do not have permissions on the [main ets-cdb10 repository](https://github.com/opengeospatial/ets-cdb10) to tag issues with milestone "0.3". I also cannot push the commit with the release notes; it is on my fork: https://github.com/GeoSensorWebLab/ets-cdb10

Would you prefer I make a pull request for the "release notes" commit, or manually use git to pick that commit?

**Comment by dstenger** [comment]
@openfirmware Do you want to become test lead of this test suite (please see https://github.com/opengeospatial/cite/wiki/CITE-Introduction-Roles-and-Responsibilities#leads)?
If this is the case,  I am definitely in favour of providing permissions to the repository to you.

**Comment by openfirmware** [comment]
@dstenger Sure, that works for me.

**Comment by openfirmware** [comment]
Hi @dstenger, any update on this? I have some changes ready for a release soon, it would be great to make a tagged release on the main repository.

**Comment by openfirmware** [comment]
I see that I have already been added to the "cdb_team" for the repository. Thanks!

**Comment by dstenger** [comment]
Thank you for your effort!

However, we usually close the issues when the test suite is installed on Beta environment.
You can mark that you are finished with your work by setting label `approved-by-test-lead`.

For further information please see: https://github.com/opengeospatial/cite/wiki/Releasing-Tests-to-the-OGC-Testing-Infrastructure#test-lead-release-checklist

**Comment by dstenger** [comment]
@openfirmware 

I realized that version 0.4 is current revision. So, I updated the title of this issue.

Thank you for already executing the Maven release plugin. However, if we use our Jenkins for that, we can deploy artefacts to Central Maven Repository and Docker Images to Docker Hub at the same time.
* https://github.com/opengeospatial/cite/wiki/How-to-create-releases-with-Maven
* https://github.com/opengeospatial/cite/wiki/How-to-create-Docker-Images-of-test-suites

Maybe, the Docker mechanism might be interesting for you as well (testing purposes etc.)?

Can tag 0.4 be installed the same way other test suites are installed?

**Comment by openfirmware** [comment]
Hi Dirk,

Yes, tag 0.4 has the same installation process as the previous versions.

For Docker, there is an additional consideration in that the user will have to mount the CDB they are testing into the Docker container, and then supply the container's path to the CDB to the test suite.
