### ISSUE TITLE
NSG WMTS 1.0 revision 0.4 in Beta

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/te-releases#273]
https://github.com/opengeospatial/ets-wmts10-nsg/milestone/4

**Comment by dstenger** [comment]
#### Prepare release (for each test suite individually)

- [x] The master branch should contain the latest "stable" version. Make sure all verified pull requests are merged.
- [x] Make sure it builds properly running `mvn clean install site -Dsource=8 -Pintegration-tests,docker`.
- [ ] Test locally the master branch with the [reference implementation](https://github.com/opengeospatial/cite/wiki/Reference-Implementations), if there is one. If there is none, any other implementation can also be used for a local test.
	- If it is OK, continue, if not create or update an issue, in the issue tracker of that test.
- [x] Review closed issues to be included in the release. 
	- Update title if appropriate.
	- Tag, if they are not tagged with the milestone number.
- [x] Update release notes, usually the file is at `src/site/asciidoc/changelog.adoc`.
	- Add a new title for the revision, if there is not one already.
	- Copy the issues to be included in the release, link and title.
	- Add any other highlights.
- [x] Create a new issue in the [OGC release tracker](https://github.com/opengeospatial/te-releases/issues) and set label `approved-by-test-lead`.
	- Write a title for the issue. It should contain: [Abbreviation] [version] revision [revision] in *Beta*. For example: WFS 1.1 revision 1.23 in Beta. It should always be in Beta. OGC staff will create the issue related to making the releases in the production, official web site.

**Comment by dstenger** [comment]
#### Create release (for each test suite individually)

- [x] In the [OGC release tracker](https://github.com/opengeospatial/te-releases/issues) assign the issue to a milestone.
- Do the release. Process involves creating a revision based on the pom.xml version, updating the GitHub page, tag, and updating the revision on the pom for the next release. 
   - [x] Check if Maven configuration has been updated: [How to create Releases with Maven](https://github.com/opengeospatial/cite/wiki/How-to-create-Releases-with-Maven).
   - [x] Create release with [Jenkins](http://build.opengeospatial.org/jenkins/).
- [x] Close milestone in the ETS issue tracker.
- [x] Set label `ready-for-installation`.
