### ISSUE TITLE
GeoPackage 1.2 revision 1.1 in Beta

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/te-releases#280]
https://github.com/opengeospatial/ets-gpkg12/milestone/8

**Comment by dstenger** [comment]
TODO: Create Jenkins Test Job (https://github.com/opengeospatial/ets-gpkg12/issues/89).

**Comment by dstenger** [comment]
TODO: Create Docker Hub repository.

**Comment by dstenger** [comment]
#### Prepare release (for each test suite individually)

- [ ] The master branch should contain the latest "stable" version. Make sure all verified pull requests are merged.
- [ ] Make sure it builds properly running `mvn clean install site -Pintegration-tests,docker`.
- [ ] Test locally the master branch with the [reference implementation](https://github.com/opengeospatial/cite/wiki/Reference-Implementations), if there is one.
	- If it is OK, continue, if not create or update an issue, in the issue tracker of that test.
- [ ] Review closed issues to be included in the release. 
	- Update title if appropriate.
	- Tag, if they are not tagged with the milestone number.
- [ ] Update release notes, usually the file is at src/site/markdown/relnotes.md.
	- Add a new title for the revision, if there is not one already.
	- Copy the issues to be included in the release, link and title.
	- Add any other highlights.
- [ ] Create a new issue in the [OGC release tracker](https://github.com/opengeospatial/te-releases/issues) and set label `approved-by-test-lead`.
	- Write a title for the issue should containing: [Abbreviation] [version] revision [revision] in *Beta*. For example: WFS 1.1 revision 1.23 in Beta. It should always be in Beta. OGC staff will create the issue related to making the releases in the production, official web site.

**Comment by dstenger** [comment]
Docker Hub repository was created: https://hub.docker.com/r/ogccite/ets-gpkg12

**Comment by dstenger** [comment]
SoapUI tests were fixed: https://github.com/opengeospatial/ets-gpkg12/commit/7fec1f8e326fc1e1cde8e332b06bab0e3e3c8d18

**Comment by dstenger** [comment]
Jenkins Test Jobs were created:
* http://build.opengeospatial.org/jenkins/view/test/job/beta-ets-gpk12-test/
* http://build.opengeospatial.org/jenkins/view/test/job/prod-ets-gpk12-test/
