### ISSUE TITLE
GeoPose 1.0 revision 0.1 in Beta

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/te-releases#394]
#### Prepare release (for each test suite individually)

- [x] The master branch should contain the latest "stable" version. Make sure all verified pull requests are merged.
- [x] Make sure it builds properly running `mvn clean install site -Pintegration-tests,docker`.
- [x] Test locally the master branch with the [reference implementation](https://github.com/opengeospatial/cite/wiki/Reference-Implementations), if there is one. If there is none, any other implementation can also be used for a local test.
	- If it is OK, continue, if not create or update an issue, in the issue tracker of that test.
- [x] Review closed issues to be included in the release. 
	- Update title if appropriate.
	- Tag, if they are not tagged with the milestone number.
- [x] Update release notes, usually the file is at src/site/asciidoc/changelog.adoc.
	- Add a new title for the revision, if there is not one already.
	- Copy the issues to be included in the release, link and title.
	- Add any other highlights.
- [x] Create a new issue in the [OGC release tracker](https://github.com/opengeospatial/te-releases/issues) and set label `approved-by-test-lead`.
	- Write a title for the issue should containing: [Abbreviation] [version] revision [revision] in *Beta*. For example: WFS 1.1 revision 1.23 in Beta. It should always be in Beta. OGC staff will create the issue related to making the releases in the production, official web site.

**Comment by dstenger** [comment]
## Checked dependencies of test suite

Following dependencies will cause conflicts with Beta:
* jackson-databind-2.14.0.jar (Beta: jackson-databind-2.12.1.jar)
* jackson-annotations-2.14.0.jar (Beta: jackson-annotations-2.12.1.jar)
* jackson-core-2.14.0.jar (Beta: jackson-core-2.12.1.jar)
* slf4j-api-1.7.36.jar (Beta: slf4j-api-1.7.30.jar)
* commons-lang3-3.12.0.jar (Beta: commons-lang3-3.11.jar)

**Comment by dstenger** [comment]
Also, I recognized that an outdated TEAM Engine version is used (4.9) and the outdated dependency ets-common as parent.

Created pull requests/issues:
* Set dependencyManagement to align dependencies with other test suites: https://github.com/opengeospatial/ets-geopose10/pull/12
* Updated TEAM Engine version: https://github.com/opengeospatial/ets-geopose10/pull/10
* Issue to remove outdated ets-common: https://github.com/opengeospatial/ets-geopose10/issues/11

@ghobona Can you please review those pull requests/ issues?

@ghobona I do not have write access to ets-geopose10 repository. Can you please grant it to me so that I can create releases?

**Comment by ghobona** [comment]
@dstenger You have now been granted `write` access to the ets-geopose10 repository.

**Comment by ghobona** [comment]
@dstenger I have now approved PR#10 and PR#12.

**Comment by ghobona** [comment]
2023-01-26 CITE meeting

* To keep ets-common in this release. It will be removed in the next release.
* @ghobona to fix https://github.com/opengeospatial/ets-geopose10/issues/13

**Comment by ghobona** [comment]
@dstenger Here is the Pull Request https://github.com/opengeospatial/ets-geopose10/pull/14 .

Please merge it and continue with the release.

**Comment by dstenger** [comment]
#### Create release (for each test suite individually)

- [x] In the [OGC release tracker](https://github.com/opengeospatial/te-releases/issues) assign the issue to a milestone.
- Do the release. Process involves creating a revision based on the pom.xml version, updating the GitHub page, tag, and updating the revision on the pom for the next release. 
   - [x] Check if Maven configuration has been updated: [How to create Releases with Maven](https://github.com/opengeospatial/cite/wiki/How-to-create-Releases-with-Maven).
   - [x] Create release with [Jenkins](http://build.opengeospatial.org/jenkins/).
- [x] Close milestone in the ETS issue tracker.
- [x] Set label `ready-for-installation`.
